// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHeJpQFj23ngtOzXorb94BXp7R6Jo-gxI',
    appId: '1:797649141601:web:3b8fb326427411299f8f20',
    messagingSenderId: '797649141601',
    projectId: 'flutterproject-502eb',
    authDomain: 'flutterproject-502eb.firebaseapp.com',
    storageBucket: 'flutterproject-502eb.appspot.com',
    measurementId: 'G-RSZ5KH0HGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG52GhJ9MhcDe30GGXVMCQZt1xCYL-Pe0',
    appId: '1:797649141601:android:a86272628d8baa769f8f20',
    messagingSenderId: '797649141601',
    projectId: 'flutterproject-502eb',
    storageBucket: 'flutterproject-502eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbuFO558Z6p3Y5t7CEh5QKnmfyLRm876U',
    appId: '1:797649141601:ios:51f1ae15d4f31f149f8f20',
    messagingSenderId: '797649141601',
    projectId: 'flutterproject-502eb',
    storageBucket: 'flutterproject-502eb.appspot.com',
    iosClientId: '797649141601-6f20lrj3nr08ug72ah9tmo87kjn4a7df.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbuFO558Z6p3Y5t7CEh5QKnmfyLRm876U',
    appId: '1:797649141601:ios:51f1ae15d4f31f149f8f20',
    messagingSenderId: '797649141601',
    projectId: 'flutterproject-502eb',
    storageBucket: 'flutterproject-502eb.appspot.com',
    iosClientId: '797649141601-6f20lrj3nr08ug72ah9tmo87kjn4a7df.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
